title: clean-charts API Reference
description: Python library for generating premium, publication-quality charts.
theme: just-the-docs
remote_theme: just-the-docs/just-the-docs

url: "" # e.g. "https://your-username.github.io"
baseurl: "" # e.g. "/clean-charts-docs"

color_scheme: auto

# Aux links for the upper right navigation
aux_links:
  "clean-charts pypi": "https://pypi.org/project/clean-charts/"

# Footer
footer_content: "clean-charts &copy; 2026. Distributed under the MIT License."
